#!/bin/bash -e

# Enable debugging for troubleshooting
if [[ "$DEBUG" == "true" ]]; then
  set -ex
fi

# Constants
NETWORK_CONFIG_DIR="/etc/systemd/network"
NETWORK_CONFIG_FILE="$NETWORK_CONFIG_DIR/10-eth0.network"
BACKUP_FILE="$NETWORK_CONFIG_FILE.bak"
PING_TARGET="8.8.8.8"

# --- Helpers ---

print_usage() {
  echo "Usage: $0 <IP_ADDRESS> <NETMASK> <GATEWAY> <DNS>"
  echo "Examples:"
  echo "  $0 192.168.1.100 24 192.168.1.1 8.8.8.8"
  echo "  $0 192.168.1.100 255.255.255.0 192.168.1.1 '1.1.1.1,8.8.8.8'"
}

validate_ip() {
  local ip=$1
  [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || { echo "Error: $ip is not a valid IPv4 format."; exit 1; }
  IFS=. read -r a b c d <<<"$ip"
  for o in "$a" "$b" "$c" "$d"; do
    [[ "$o" -ge 0 && "$o" -le 255 ]] || { echo "Error: $ip has out-of-range octet."; exit 1; }
  done
}

# Convert netmask to CIDR. Accepts "24", "/24", or dotted "255.255.255.0"
to_cidr() {
  local mask="$1"
  if [[ "$mask" =~ ^/?([0-9]{1,2})$ ]]; then
    echo "${BASH_REMATCH[1]}"
    return 0
  fi
  # dotted form
  validate_ip "$mask"
  IFS=. read -r o1 o2 o3 o4 <<<"$mask"
  local ones_in_octet() {
    case "$1" in
      255) echo 8;;
      254) echo 7;;
      252) echo 6;;
      248) echo 5;;
      240) echo 4;;
      224) echo 3;;
      192) echo 2;;
      128) echo 1;;
      0)   echo 0;;
      *)   echo -1;;
    esac
  }
  local n1 n2 n3 n4
  n1=$(ones_in_octet "$o1"); n2=$(ones_in_octet "$o2"); n3=$(ones_in_octet "$o3"); n4=$(ones_in_octet "$o4")
  for n in "$n1" "$n2" "$n3" "$n4"; do
    [[ "$n" -ge 0 ]] || { echo "Error: Non-contiguous or invalid netmask: $mask"; exit 1; }
  done
  # Enforce contiguity: once we see <8, remainder must be zeros
  local parts=("$n1" "$n2" "$n3" "$n4"); local seen_partial=0
  for i in {0..3}; do
    if (( parts[i] == 8 )); then
      [[ $seen_partial -eq 0 ]] || { echo "Error: Non-contiguous netmask: $mask"; exit 1; }
    elif (( parts[i] > 0 && parts[i] < 8 )); then
      [[ $seen_partial -eq 0 ]] || { echo "Error: Non-contiguous netmask: $mask"; exit 1; }
      seen_partial=1
    else # == 0
      # after zero, all remaining must be zero
      for j in $(seq $((i+1)) 3); do
        (( parts[j] == 0 )) || { echo "Error: Non-contiguous netmask: $mask"; exit 1; }
      done
      break
    fi
  done
  echo $(( n1 + n2 + n3 + n4 ))
}

# Backup the current configuration
backup_config() {
  if [ -f "$NETWORK_CONFIG_FILE" ] && [ ! -f "$BACKUP_FILE" ]; then
    sudo cp "$NETWORK_CONFIG_FILE" "$BACKUP_FILE"
    echo "Backup of current configuration saved to $BACKUP_FILE."
  fi
}

# Restore the previous configuration
restore_config() {
  if [ -f "$BACKUP_FILE" ]; then
    sudo cp "$BACKUP_FILE" "$NETWORK_CONFIG_FILE"
    echo "Previous configuration restored."
    sudo systemctl reload systemd-networkd || sudo systemctl restart systemd-networkd
  else
    echo "No backup configuration found. Cannot restore."
  fi
}

# Apply the new network configuration
apply_config() {
  local ip=$1
  local cidr=$2
  local gateway=$3
  local dns_line=$4
  STAMP="$(date +%Y%m%d-%H%M%S)"

  sudo mkdir -p "$NETWORK_CONFIG_DIR"

  sudo bash -c "cat > '$NETWORK_CONFIG_FILE'" <<EOF
# Generated by network-setup.sh on ${STAMP}
[Match]
Name=eth0

[Link]
WakeOnLan=off

[Network]
Address=${ip}/${cidr}
Gateway=${gateway}
DNS=${dns_line}
LLMNR=no
MulticastDNS=no
LinkLocalAddressing=no
RequiredForOnline=yes
EOF

  echo "New network configuration written to $NETWORK_CONFIG_FILE."
  # Softer than restart; falls back to restart if reload unsupported
  sudo systemctl reload systemd-networkd || sudo systemctl restart systemd-networkd
  # Wait for carrier/address to settle a bit
  sleep 2
}

# Test the network connection
test_connection() {
  if ping -c 1 -W 2 "$PING_TARGET" &> /dev/null; then
    echo "Network connection is active."
    return 0
  else
    echo "Network connection test failed."
    return 1
  fi
}

# --- Main ---

IP_ADDRESS=$1
NETMASK=$2
GATEWAY=$3
DNS=$4

if [[ -z "$IP_ADDRESS" || -z "$NETMASK" || -z "$GATEWAY" || -z "$DNS" ]]; then
  echo "Error: All arguments (IP_ADDRESS, NETMASK, GATEWAY, DNS) must be provided."
  print_usage
  exit 1
fi

validate_ip "$IP_ADDRESS"
validate_ip "$GATEWAY"

# Normalize netmask to CIDR
CIDR="$(to_cidr "$NETMASK")"
[[ "$CIDR" -ge 0 && "$CIDR" -le 32 ]] || { echo "Error: Invalid CIDR: $CIDR"; exit 1; }

# Allow multiple DNS (comma or space separated). Validate each.
DNS_LINE=""
# Replace commas with spaces, collapse repeats
DNS_NORMALIZED="$(echo "$DNS" | tr ',' ' ' | xargs -n999 echo)"
for d in $DNS_NORMALIZED; do
  validate_ip "$d"
  DNS_LINE+="$d "
done
DNS_LINE="${DNS_LINE%% }"

# Backup current configuration
backup_config

# Apply new configuration
apply_config "$IP_ADDRESS" "$CIDR" "$GATEWAY" "$DNS_LINE"

# Test the connection
if test_connection; then
  echo "Network configuration successful."
else
  echo "Network configuration failed. Reverting to previous configuration."
  restore_config
  exit 1
fi
